### ISSUE TITLE
How to disable code highlighting feature

### ISSUE THREAD

**Issue by omid** [uiwjs/react-md-editor#586]
Code highlighting feature is very large. And I actually don't need it at all.
How to disable it completely if we don't want to use code highlighting feature at all?
(I'm using Vite)

**Comment by jaywcjlove** [comment]
@omid 

https://github.com/uiwjs/react-md-editor/blob/a3f09f313cf64116c8f78053d81e9e54fba0a417/core/src/Editor.tsx#L113-L117

**Comment by omid** [comment]
Thanks, but I still see them:
![image](https://github.com/uiwjs/react-md-editor/assets/45714/f0c129e6-35f6-4794-ac45-52901f6d97ce)

**Comment by jaywcjlove** [comment]
@omid This is the code highlighting language pack with markdown preview

**Comment by omid** [comment]
Ok, how can I remove that from the package @jaywcjlove ?

**Comment by omid** [comment]
Output of `npm ls refractor` is:
![image](https://github.com/uiwjs/react-md-editor/assets/45714/b564c314-e494-48dd-a9e8-2107792e01e9)

**Comment by jaywcjlove** [comment]
@omid  If you remove the default code highlighting, it will disappear.

![image](https://github.com/uiwjs/react-md-editor/assets/1680273/3937ab37-018b-41c4-902f-809bc3456ca6)

It's not easy to get rid of this package.

**Comment by omid** [comment]
How can I remove the default code highlighting?

I set highlightEnable as `false`. What else?

**Comment by jaywcjlove** [comment]
@omid I thought of a perfect solution

Provide a new component that does not contain `rehype-prism-plus`. It will not be included in the packaging code after testing and packaging.

```jsx
import MDEditor from '@uiw/react-md-editor/nohighlight';
```

**Comment by jaywcjlove** [comment]
@omid upgrade `v3.25.0`


### Remove Code Highlight

The following example can help you _exclude code highlighting code_ from being included in the bundle. `@uiw/react-md-editor/nohighlight` component does not contain the ~~`rehype-prism-plus`~~ code highlighting package, ~~`highlightEnable`~~, ~~`showLineNumbers`~~ and ~~`highlight line`~~ functions will no longer work. ([#586](https://github.com/uiwjs/react-md-editor/issues/586))

```jsx mdx:preview
import React from "react";
import MDEditor from '@uiw/react-md-editor/nohighlight';

const code = `**Hello world!!!**
\`\`\`js
function demo() {}
\`\`\`
`

export default function App() {
  const [value, setValue] = React.useState(code);
  return (
    <div className="container">
      <MDEditor
        value={value}
        onChange={setValue}
      />
      <MDEditor.Markdown source={value} style={{ whiteSpace: 'pre-wrap' }} />
    </div>
  );
}
```

**Comment by omid** [comment]
Thanks a lot @jaywcjlove. It works 🎉

Now the package is 0.5MB smaller in gzip (1MB uncompressed).

There is a tiny issue.

After I upgrade to 3.25.0 and apply the changes.
![image](https://github.com/uiwjs/react-md-editor/assets/45714/5be4ead0-d3a3-4d2a-a267-334dd133a205)


I'm getting this error:
```
src/components/text-editor/text-editor.tsx:2:22 - error TS2307: Cannot find module '@uiw/react-md-editor/nohighlight' or its corresponding type declarations.

2 import MDEditor from '@uiw/react-md-editor/nohighlight';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in src/components/text-editor/text-editor.tsx:2
```

So I needed to add a `// @ts-ignore` above it :/

**Comment by jaywcjlove** [comment]
@omid Upgrade `v3.25.1`

**Comment by omid** [comment]
All is good, thanks @jaywcjlove
